### ISSUE TITLE
可以连视频标题一起下载么，视频名称只是单纯的番号

### ISSUE THREAD

**Issue by sewujishipin** [OldRayHu/JableTV#1]
可以连视频标题一起下载么，视频名称只是单纯的番号

**Comment by OldRayHu** [comment]
查看beta分支，已经在beta分支中更新该功能，使用正常的话请反馈

**Comment by sewujishipin** [comment]
> 查看beta分支，已经在beta分支中更新功能，使用正常的话请反馈

大佬这么晚不睡阿~感谢。我明天测试后反馈下~  辛苦啦
